<program>     ::= <pick_cmd> "start" <stmt_list> "end"
<pick_cmd>    ::= "pick" <pokemon_name>
<stmt_list>   ::= <stmt> | <stmt> <stmt_list>
<stmt>        ::= <if_stmt> | <while_stmt> | <special_cmd> | <cure_cmd> | <normal_cmd>
<if_stmt>     ::= "if" <condition> ":" <stmt_list> "else" ":" <stmt_list> "end"
<while_stmt>  ::= "while" <condition> ":" <stmt_list> "end"
<special_cmd> ::= "special"
<normal_cmd>  ::= "normal"
<cure_cmd>    ::= "cure"
<condition>   ::= <operand> <comp_op> <operand>
<operand>     ::= "life" | "attack" | "enemy_life" | "enemy_attack" | <number>
<comp_op>     ::= ">" | "<" | "=" | ">=" | "<="
<pokemon_name>::= "Pikachu" | "Charizard" | "Bulbasaur" | "Blastoise" | "Eevee" | 
                  "Gengar" | "Snorlax" | "Lucario" | "Greninja" | "Sceptile" | "Infernape" | 
                  "Lapras" | "Drapion" | "Rhydon" | "Talonflame" | "Alakazam" | "Mewtwo" |
                  "Heracross" | "Onix" | "Dragonite" | "Garchomp" | "Rayquaza" | "Zoroark" |
                  "Gardevoir" | "Arceus"
<number>      ::= <digit> | <digit> <number>
<digit>       ::= "0" | ... | "9"
